language: generic

services:
  - docker

before_install:
  - docker build -t hnskde/imongr-base-r .
  - docker run -d -ti --name imongr-base-r hnskde/imongr-base-r

script:
  - docker ps | grep -q imongr-base-r

deploy:
  - provider: script
    script: bash docker_push.sh
    skip_cleanup: true
    on:
      # 'tags: true' maybe added
      branch: master
